### ISSUE TITLE
Migrating: 2022_04_08_081403_create_attendances_table     Illuminate\Database\QueryException 

### ISSUE THREAD

**Issue by SushmitSingh** [omakei/hrms-filament#1]
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:716
    712▕         // If an exception occurs when attempting to run a query, we'll format the error
    713▕         // message to include the bindings with SQL, which will make this exception a
    714▕         // lot more helpful to the developer instead of just the database's errors.
    715▕         catch (Exception $e) {
  ➜ 716▕             throw new QueryException(
    717▕                 $query, $this->prepareBindings($bindings), $e
    718▕             );
    719▕         }
    720▕     }

  SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name 'is_confirmed ' (SQL: create table `attendances` (`id` bigint unsigned not null auto_increment primary key, `employee_id` bigint unsigned not null, `recorded_by` bigint unsigned not null, `shift_id` bigint unsigned not null, `time_id` time null, `time_out` time null, `status` varchar(255) not null, `is_confirmed ` tinyint(1) not null default '0', `recorded_at` timestamp not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by omakei** [comment]
I already fix the problem you can pull new changes and run migration again
